language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: qLMcymSZjknO98Q6hA31rFSfQvcKWzGOd3OwFF+mgRTeXpNeBDU7zWRgDTgsgWWqScgJffI9IOGnI8gTyH8xM8R2qTL6S/7TGOYvLI2hmE8K26U29fIbxlaCSt+807PKxP5chgSH04t25oL/cqc6BscJHze2tV5nU/MhSS8/H1tmdrtZmWZTG/nyyjOQhmLp/RaPZ4T2hnAzLT5u0cJRPmH7d96AUzPSGSJKQgDa6MHa81ukGpFf6jRgTwWbNy0/dB/T6oqKY+rlCRvKYeUNGnq02c2tjDTyTC1WoxEQqZwx91bw4fIpimNv2HfjJ+wWkT8IHi8xf3eG7iNmjRpAg2kfayuSsYMxWemcLzgn7CYLC3l5JdyDh5/B+ljYj0z5Dw9RfADjk+vKMSPwwA1Lw7jXxj/EZZdA+PeffqkJrcVPVy9uK9u2JeaRElWXFjiExVxS6d7ZfIur9vSfOgCuR344FJNYswH+PoyqthatMc8u/VccVhOikFnQKLXpzbAz6ZYAWP0EBiKMZ+q03VYD5E55mwLU2LQGy04NcqNBTaHK+ABDoZGd5oQc88ATe1cPfVKnE03TuknX5z0EyGk1infT3fDXiEHiSG95GQyFEUua3KkmZl8nxtmk0WQWFRfUT52Li5cnWX+m13XNI7ORg8T/px1xQhcqppvjy0+IhuQ=
  on:
    tags: true
